spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: hotel_app
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1